## 데이터 통합 및 변형 연습문제

필요 모듈 임포트

In [2]:
import numpy as np
import pandas as pd

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

#### house 폴더에 있는 세 도시의 가구별 데이터 파일들을 사용하여 도시별 데이터프레임을 생성하시오.

- 나주시

## 나주시 2004년~ 2020년 데이터

In [108]:
naju1 = pd.read_csv('data/나주시_주택현황 및 보급률(2004~2020).csv', encoding='cp949', header=[0,1,2])
naju2 = pd.read_csv('data/나주시_주택현황 및 보급률_2021년.csv', encoding='cp949')

In [110]:
naju1

  행정구역(시군)별(1)     2004                                                       \
  행정구역(시군)별(1) 가구수 (가구) 주택수 (호)                                    주택보급률 (%)
  행정구역(시군)별(1)       소계      소계   단독주택   아파트 연립주택 다세대주택 비거주용 건물내주택        소계
0          나주시    40506   41522  33063  7204  497    96        662     102.5

      2005  ...      2019     2020                                        \
  가구수 (가구)  ... 주택보급률 (%) 가구수 (가구) 주택수 (호)
        소계  ...        소계       소계      소계   단독주택 단독주택_다가구주택    아파트 연립주택
0    40506  ...     104.1    58025   59643  29587       3578  28612  291


                   주택보급률 (%)
  다세대주택 비거주용 건물내주택        소계
0   539        614     102.8

[1 rows x 151 columns]

In [114]:
naju1_T = naju1.T
naju1_T = naju1_T.unstack(level=0)
naju1_T

                               0                                            \
                            2004   2005   2006   2007   2008   2009   2010
가구수 (가구)     소계            40506  40506  41172  41277  41000  40733  41284
주택보급률 (%)    소계            102.5  102.8  103.5  104.4  104.5  105.3  103.9
주택수 (호)      다세대주택            96     10    206    169    209    217    217
             단독주택          33063  33178  32885  32856  32834  32864  32830
             단독주택_다가구주택      NaN    NaN    NaN      2      7     18     34
             비거주용 건물내주택      662    662    696   1250    963    971    965
             소계            41522  41653  42626  43112  42843  42889  42905
             아파트            7204   7223   8345   8345   8345   8345   8401
             연립주택            497    580    494    492    492    492    492
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN

                                                                            \
                            2011   2012   2013   2014   2015   2016   2017
가구수 (가구)     소계            40700  40841  41274  42886  46444  52007  52303
주택보급률 (%)    소계            100.7  104.4  114.5  105.0  107.7  109.1  105.8
주택수 (호)      다세대주택           155    330    545    513   1276    601    482
             단독주택          31176  32531  37066  32947  32958  31080  29558
             단독주택_다가구주택     1282    668    817   1518   4060    256   2769
             비거주용 건물내주택      655    584     40    611      -   1070    632
             소계            40993  42622  47272  45041  50030  56762  55321
             아파트            8596   8685   9358  10723  14906  23519  24093
             연립주택            411    492    263    247    890    492    556
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN


                            2018   2019   2020 행정구역(시군)별(1)
가구수 (가구)     소계            54872  56090  58025          NaN
주택보급률 (%)    소계            105.9  104.1  102.8          NaN
주택수 (호)      다세대주택           539    539    539          NaN
             단독주택          29650  29840  29587          NaN
             단독주택_다가구주택     3019   3301   3578          NaN
             비거주용 건물내주택      636    608    614          NaN
             소계            58133  58412  59643          NaN
             아파트           27001  27134  28612          NaN
             연립주택            307    291    291          NaN
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN          나주시

In [139]:
# naju1_T.drop(['행정구역(시군)별(1)','행정구역(시군)별(1)'], inplace=True)
# naju1_T.drop(columns=[(0,'행정구역(시군)별(1)')], inplace=True)
naju1 = naju1_T.droplevel(level=0, axis=1)
naju1

                       2004   2005   2006   2007   2008   2009   2010   2011  \
가구수 (가구)  소계          40506  40506  41172  41277  41000  40733  41284  40700
주택보급률 (%) 소계          102.5  102.8  103.5  104.4  104.5  105.3  103.9  100.7
주택수 (호)   다세대주택          96     10    206    169    209    217    217    155
          단독주택        33063  33178  32885  32856  32834  32864  32830  31176
          단독주택_다가구주택    NaN    NaN    NaN      2      7     18     34   1282
          비거주용 건물내주택    662    662    696   1250    963    971    965    655
          소계          41522  41653  42626  43112  42843  42889  42905  40993
          아파트          7204   7223   8345   8345   8345   8345   8401   8596
          연립주택          497    580    494    492    492    492    492    411

                       2012   2013   2014   2015   2016   2017   2018   2019  \
가구수 (가구)  소계          40841  41274  42886  46444  52007  52303  54872  56090
주택보급률 (%) 소계          104.4  114.5  105.0  107.7  109.1  105.8  105.9  104.1
주택수 (호)   다세대주택         330    545    513   1276    601    482    539    539
          단독주택        32531  37066  32947  32958  31080  29558  29650  29840
          단독주택_다가구주택    668    817   1518   4060    256   2769   3019   3301
          비거주용 건물내주택    584     40    611      -   1070    632    636    608
          소계          42622  47272  45041  50030  56762  55321  58133  58412
          아파트          8685   9358  10723  14906  23519  24093  27001  27134
          연립주택          492    263    247    890    492    556    307    291

                       2020
가구수 (가구)  소계          58025
주택보급률 (%) 소계          102.8
주택수 (호)   다세대주택         539
          단독주택        29587
          단독주택_다가구주택   3578
          비거주용 건물내주택    614
          소계          59643
          아파트         28612
          연립주택          291

In [140]:
index = ['일반가구수(A)(가구)', '주택보급률(B)/(A)*100(%)', '다세대주택(호)', '단독주택', '다가구주택(호)', 
         '비거주용건물내주택(호)', '주택수(B)(호)', '아파트(호)', '연립주택(호)']

In [141]:
naju1.index = index
naju1

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
일반가구수(A)(가구),40506,40506,41172,41277,41000,40733,41284,40700,40841,41274,42886,46444,52007,52303,54872,56090,58025
주택보급률(B)/(A)*100(%),102.5,102.8,103.5,104.4,104.5,105.3,103.9,100.7,104.4,114.5,105.0,107.7,109.1,105.8,105.9,104.1,102.8
다세대주택(호),96,10,206,169,209,217,217,155,330,545,513,1276,601,482,539,539,539
단독주택,33063,33178,32885,32856,32834,32864,32830,31176,32531,37066,32947,32958,31080,29558,29650,29840,29587
다가구주택(호),NaN,NaN,NaN,2,7,18,34,1282,668,817,1518,4060,256,2769,3019,3301,3578
비거주용건물내주택(호),662,662,696,1250,963,971,965,655,584,40,611,-,1070,632,636,608,614
주택수(B)(호),41522,41653,42626,43112,42843,42889,42905,40993,42622,47272,45041,50030,56762,55321,58133,58412,59643
아파트(호),7204,7223,8345,8345,8345,8345,8401,8596,8685,9358,10723,14906,23519,24093,27001,27134,28612
연립주택(호),497,580,494,492,492,492,492,411,492,263,247,890,492,556,307,291,291

## 나주시 2021년 데이터

In [155]:
naju2_T = naju2.T
naju2_T.drop(index='데이터기준일자', inplace=True)
naju2_T.columns = ['2021']
naju2_T.loc['주택수'] = naju2_T.loc['다세대주택'] + naju2_T.loc['단독주택'] + naju2_T.loc['다가구주택'] + naju2_T.loc['비거주용 건물내 주택'] + naju2_T.loc['연립주택']
naju3 = naju2_T.reindex(index=['가구수','주택보급률', '주택수', '다세대주택','단독주택','다가구주택','비거주용 건물내 주택','아파트','연립주택'])
naju3.index = index
naju3

                      2021
일반가구수(A)(가구)         59292
주택보급률(B)/(A)*100(%)    108
다세대주택(호)             35316
단독주택                   539
다가구주택(호)             29952
비거주용건물내주택(호)          3925
주택수(B)(호)              609
아파트(호)               28612
연립주택(호)                291

In [156]:
pd.concat([naju1, naju3], axis=1, join='inner')

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
일반가구수(A)(가구),40506,40506,41172,41277,41000,40733,41284,40700,40841,41274,42886,46444,52007,52303,54872,56090,58025,59292
주택보급률(B)/(A)*100(%),102.5,102.8,103.5,104.4,104.5,105.3,103.9,100.7,104.4,114.5,105.0,107.7,109.1,105.8,105.9,104.1,102.8,108
다세대주택(호),96,10,206,169,209,217,217,155,330,545,513,1276,601,482,539,539,539,35316
단독주택,33063,33178,32885,32856,32834,32864,32830,31176,32531,37066,32947,32958,31080,29558,29650,29840,29587,539
다가구주택(호),NaN,NaN,NaN,2,7,18,34,1282,668,817,1518,4060,256,2769,3019,3301,3578,29952
비거주용건물내주택(호),662,662,696,1250,963,971,965,655,584,40,611,-,1070,632,636,608,614,3925
주택수(B)(호),41522,41653,42626,43112,42843,42889,42905,40993,42622,47272,45041,50030,56762,55321,58133,58412,59643,609
아파트(호),7204,7223,8345,8345,8345,8345,8401,8596,8685,9358,10723,14906,23519,24093,27001,27134,28612,28612
연립주택(호),497,580,494,492,492,492,492,411,492,263,247,890,492,556,307,291,291,291

- 서산시

In [160]:
seosan1 = pd.read_csv('data/서산시_주택현황 및 보급률(2002~2007).csv', encoding='cp949', header=[0,1,2])
seosan2 = pd.read_csv('data/서산시_주택현황 및 보급률(2008~2012).csv', encoding='cp949', header=[0,1,2])
seosan3 = pd.read_csv('data/서산시_주택현황 및 보급률(2013~2022).csv', encoding='cp949', header=[0,1,2])

In [161]:
seosan1

  행정구역(시군)별(1)     2002                                                    \
  행정구역(시군)별(1) 세대수 (세대) 주택수 (호)
  행정구역(시군)별(1)       소계      소계   단독주택 다가구주택    아파트  연립주택 다세대주택 비거주용건물내주택
0          서산시    50286   49394  28887   135  16293  1543  2536      1358

             ...      2006               2007                              \
  주택보급률 (%)  ... 주택보급률 (%) 보통가구(보급율 산정용) (가구) 주택수 (호)
         소계  ...        소계                 소계      소계   단독주택 다가구주택    아파트
0      98.2  ...       135              39161   56374  23057   897  27170


                        주택보급률 (%)
   연립주택 다세대주택 비거주용건물내주택        소계
0  2639  2451      1057       144

[1 rows x 57 columns]

In [163]:
seosan1_T = seosan1.T
seosan1_T = seosan1_T.unstack(level=0)
seosan1_T

                                     0                                     \
                                  2002   2003   2004   2005   2006   2007
가구수 (가구)           1인가구            NaN    NaN    NaN  10502    NaN    NaN
                   비혈연가구           NaN    NaN    NaN   1107    NaN    NaN
                   일반가구            NaN    NaN    NaN  50380    NaN    NaN
보통가구(보급율 산정용) (가구) 소계              NaN    NaN    NaN  38771  38980  39161
세대수 (세대)           소계            50286  47864  48548    NaN    NaN    NaN
주택보급률 (%)          소계             98.2    101  100.2    122    135    144
주택수 (호)            다가구주택           135    186    250    NaN    875    897
                   다세대주택          2536   1574   1673   2269   2435   2451
                   단독주택          28887  25234  25363  23211  23208  23057
                   비거주용건물내주택      1358   1352   1379    808    810   1057
                   소계            49394  48320  48636  47398  52626  56374
                   아파트           16293  18105  18121  18571  23634  27170
                   연립주택           1543   3221   3229   2539   2539   2639
행정구역(시군)별(1)       행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN    NaN


                                행정구역(시군)별(1)
가구수 (가구)           1인가구                  NaN
                   비혈연가구                 NaN
                   일반가구                  NaN
보통가구(보급율 산정용) (가구) 소계                    NaN
세대수 (세대)           소계                    NaN
주택보급률 (%)          소계                    NaN
주택수 (호)            다가구주택                 NaN
                   다세대주택                 NaN
                   단독주택                  NaN
                   비거주용건물내주택             NaN
                   소계                    NaN
                   아파트                   NaN
                   연립주택                  NaN
행정구역(시군)별(1)       행정구역(시군)별(1)          서산시

In [165]:
seosan1_T.drop(index=['행정구역(시군)별(1)','행정구역(시군)별(1)'], columns=[(0,'행정구역(시군)별(1)')], inplace=True)
seosan1 = seosan1_T.droplevel(level=0, axis=1)
seosan1.drop(index='가구수 (가구)', inplace=True)
seosan1

                               2002   2003   2004   2005   2006   2007
보통가구(보급율 산정용) (가구) 소계           NaN    NaN    NaN  38771  38980  39161
세대수 (세대)           소계         50286  47864  48548    NaN    NaN    NaN
주택보급률 (%)          소계          98.2    101  100.2    122    135    144
주택수 (호)            다가구주택        135    186    250    NaN    875    897
                   다세대주택       2536   1574   1673   2269   2435   2451
                   단독주택       28887  25234  25363  23211  23208  23057
                   비거주용건물내주택   1358   1352   1379    808    810   1057
                   소계         49394  48320  48636  47398  52626  56374
                   아파트        16293  18105  18121  18571  23634  27170
                   연립주택        1543   3221   3229   2539   2539   2639

In [166]:
index2 = ['일반가구수(A)(가구)', '세대수', '주택보급률(B)/(A)*100(%)', '다가구주택(호)', '다세대주택(호)', '단독주택',
          '비거주용건물내주택(호)', '주택수(B)(호)', '아파트(호)', '연립주택(호)']

In [168]:
seosan1.index = index2
seosan1

                      2002   2003   2004   2005   2006   2007
일반가구수(A)(가구)           NaN    NaN    NaN  38771  38980  39161
세대수                  50286  47864  48548    NaN    NaN    NaN
주택보급률(B)/(A)*100(%)   98.2    101  100.2    122    135    144
다가구주택(호)               135    186    250    NaN    875    897
다세대주택(호)              2536   1574   1673   2269   2435   2451
단독주택                 28887  25234  25363  23211  23208  23057
비거주용건물내주택(호)          1358   1352   1379    808    810   1057
주택수(B)(호)            49394  48320  48636  47398  52626  56374
아파트(호)               16293  18105  18121  18571  23634  27170
연립주택(호)               1543   3221   3229   2539   2539   2639

In [169]:
seosan2

  행정구역(시군)별(1)       2008                                                      \
  행정구역(시군)별(1) 일반가구수 (가구) 주택수 (호)
  행정구역(시군)별(1)         소계      소계   단독주택 다가구주택    아파트  연립주택 다세대주택 비거주용건물 내 주택
0          서산시      51585   61827  28502  6173  27170  2639  2459        1057

             ...        2011                 2012                        \
  주택보급률 (%)  ...     주택수 (호) 주택보급률 (%) 일반가구수 (가구) 주택수 (호)
         소계  ... 비거주용건물 내 주택        소계         소계      소계   단독주택  다가구주택
0       120  ...         581     108.4      62068   68506  22197  11622


                     주택보급률 (%)
     아파트  연립주택 다세대주택        소계
0  29610  2764  2313     110.4

[1 rows x 45 columns]

In [170]:
seosan2_T = seosan2.T
seosan2_T = seosan2_T.unstack(level=0)
seosan2_T

                               0
                            2008   2009   2010   2011   2012 행정구역(시군)별(1)
일반가구수 (가구)   소계            51585  51945  58274  60287  62068          NaN
주택보급률 (%)    소계              120    120   99.4  108.4  110.4          NaN
주택수 (호)      다가구주택          6173   6480   8312   9590  11622          NaN
             다세대주택          2459   2483   1744   2058   2313          NaN
             단독주택          28502  28844  27002  20780  22197          NaN
             비거주용건물 내 주택    1057   1067    737    581    NaN          NaN
             소계            61827  62203  57918  65343  68506          NaN
             아파트           27170  27170  25920  28345  29610          NaN
             연립주택           2639   2639   2515   2764   2764          NaN
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN          서산시

In [189]:
seosan2_T.drop(index=['행정구역(시군)별(1)','행정구역(시군)별(1)'], columns=[(0,'행정구역(시군)별(1)')], inplace=True)
seosan2 = seosan2_T.droplevel(level=0, axis=1)
seosan2.loc['세대수'] = np.nan
seosan2.reindex(index=['(일반가구수 (가구), 소계)', '세대수', '(주택보급률 (%), 소계)', '(주택수 (호), 다가구주택)', '(주택수 (호), 다세대주택)',
                       '(주택수 (호), 단독주택)', '(주택수 (호), 비거주용건물 내 주택)', '(주택수 (호), 소계)', '(주택수 (호), 아파트)', '(주택수 (호), 연립주택)'])
seosan2

                       2008 2009 2010 2011 2012
(일반가구수 (가구), 소계)        NaN  NaN  NaN  NaN  NaN
세대수                     NaN  NaN  NaN  NaN  NaN
(주택보급률 (%), 소계)         NaN  NaN  NaN  NaN  NaN
(주택수 (호), 다가구주택)        NaN  NaN  NaN  NaN  NaN
(주택수 (호), 다세대주택)        NaN  NaN  NaN  NaN  NaN
(주택수 (호), 단독주택)         NaN  NaN  NaN  NaN  NaN
(주택수 (호), 비거주용건물 내 주택)  NaN  NaN  NaN  NaN  NaN
(주택수 (호), 소계)           NaN  NaN  NaN  NaN  NaN
(주택수 (호), 아파트)          NaN  NaN  NaN  NaN  NaN
(주택수 (호), 연립주택)         NaN  NaN  NaN  NaN  NaN

                      2008   2009   2010   2011   2012
일반가구수(A)(가구)         51585  51945  58274  60287  62068
세대수                    NaN    NaN    NaN    NaN    NaN
주택보급률(B)/(A)*100(%)   6173   6480   8312   9590  11622
다가구주택(호)              2459   2483   1744   2058   2313
다세대주택(호)             28502  28844  27002  20780  22197
단독주택                  1057   1067    737    581    NaN
비거주용건물내주택(호)         61827  62203  57918  65343  68506
주택수(B)(호)            27170  27170  25920  28345  29610
아파트(호)                2639   2639   2515   2764   2764
연립주택(호)                NaN    NaN    NaN    NaN    NaN

In [190]:
seosan2.index = index2
seosan2

                      2008   2009   2010   2011   2012
일반가구수(A)(가구)         51585  51945  58274  60287  62068
세대수                    NaN    NaN    NaN    NaN    NaN
주택보급률(B)/(A)*100(%)   6173   6480   8312   9590  11622
다가구주택(호)              2459   2483   1744   2058   2313
다세대주택(호)             28502  28844  27002  20780  22197
단독주택                  1057   1067    737    581    NaN
비거주용건물내주택(호)         61827  62203  57918  65343  68506
주택수(B)(호)            27170  27170  25920  28345  29610
아파트(호)                2639   2639   2515   2764   2764
연립주택(호)                NaN    NaN    NaN    NaN    NaN

In [177]:
seosan3

    행정구역(읍면동)별(1)       2013                                           \
    행정구역(읍면동)별(1) 일반가구수 (가구) 주택수 (호)
    행정구역(읍면동)별(1)         소계      소계   단독주택 단독주택.1    아파트  연립주택 다세대주택
0   행정구역(읍면동)별(1)         소계      소계     소계  다가구주택     소계    소계    소계
1              합계      63902   71176  34215  12703  30983  2864  2435
2             대산읍       6408    8074   3957   1842   3610   198   229
3             인지면       3105    2820   1286     18   1467    59     -
4             부석면       2665    2407   2312     88      -    68     -
5             팔봉면       1583    1507   1493     55      2     -     -
6             지곡면       3456    3908   1577    196   2230    17    59
7             성연면       1160    1030   1007     97      -     -    12
8             음암면       4241    4475   1820     39   2017   408   207
9             운산면       2679    2525   1981     57    264   247    16
10            해미면       3794    5279   4224   2401    383   390   235
11            고북면       3258    3090   1981    153    890   175    32
12            부춘동       7754    8430   3114   2074   4707   185   305
13           동문1동      10785   11083   4806   3140   4707   666   702
14            수석동       5843    6459   1675    851   4145   194   419
15            석남동       7171   10089   2982   1692   6561   257   219

                          ...      2021       2022                        \
               주택보급률 (%)  ... 주택보급률 (%) 일반가구수 (가구) 주택수 (호)
   비거주용 건물내 주택        소계  ...        소계         소계      소계   단독주택 단독주택.1
0           소계        소계  ...        소계         소계      소계     소계  다가구주택
1          679    111.38  ...     99.47      76382   76189  23351   1442
2           80    126.00  ...         -          -       -      -      -
3            8     90.82  ...         -          -       -      -      -
4           27     90.32  ...         -          -       -      -      -
5           12     95.20  ...         -          -       -      -      -
6           25    113.08  ...         -          -       -      -      -
7           11     88.79  ...         -          -       -      -      -
8           23    105.52  ...         -          -       -      -      -
9           17     94.25  ...         -          -       -      -      -
10          47    139.14  ...         -          -       -      -      -
11          12     94.84  ...         -          -       -      -      -
12         119    108.72  ...         -          -       -      -      -
13         202    102.76  ...         -          -       -      -      -
14          26    110.54  ...         -          -       -      -      -
15          70    140.69  ...         -          -       -      -      -


                                  주택보급률 (%)
      아파트  연립주택 다세대주택 비거주용 건물내 주택        소계
0      소계    소계    소계          소계        소계
1   45034  2104  4854         846     99.75
2       -     -     -           -         -
3       -     -     -           -         -
4       -     -     -           -         -
5       -     -     -           -         -
6       -     -     -           -         -
7       -     -     -           -         -
8       -     -     -           -         -
9       -     -     -           -         -
10      -     -     -           -         -
11      -     -     -           -         -
12      -     -     -           -         -
13      -     -     -           -         -
14      -     -     -           -         -
15      -     -     -           -         -

[16 rows x 91 columns]

In [178]:
seosan3_T = seosan3.T
seosan3_T = seosan3_T.unstack(level=0)
seosan3_T

                                0                                             \
                              2013   2014   2015   2016   2017   2018   2019
일반가구수 (가구)    소계                소계     소계     소계     소계     소계     소계     소계
주택보급률 (%)     소계                소계     소계     소계     소계     소계     소계     소계
주택수 (호)       다세대주택             소계     소계     소계     소계     소계     소계     소계
              단독주택              소계     소계     소계     소계     소계     소계     소계
              단독주택.1         다가구주택  다가구주택  다가구주택  다가구주택  다가구주택  다가구주택  다가구주택
              비거주용 건물내 주택       소계     소계     소계     소계     소계     소계     소계
              소계                소계     소계     소계     소계     소계     소계     소계
              아파트               소계     소계     소계     소계     소계     소계     소계
              연립주택              소계     소계     소계     소계     소계     소계     소계
행정구역(읍면동)별(1) 행정구역(읍면동)별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN

                                                  ...      15                  \
                              2020   2021   2022  ...    2014    2015    2016
일반가구수 (가구)    소계                소계     소계     소계  ...    7309    9432   10699
주택보급률 (%)     소계                소계     소계     소계  ...  141.26  112.62  111.95
주택수 (호)       다세대주택             소계     소계     소계  ...     263     354     386
              단독주택              소계     소계     소계  ...    3121    3357    3843
              단독주택.1         다가구주택  다가구주택  다가구주택  ...    1818    2014    2246
              비거주용 건물내 주택       소계     소계     소계  ...      99      54      83
              소계                소계     소계     소계  ...   10325   10622   11977
              아파트               소계     소계     소계  ...    6561    6694    7502
              연립주택              소계     소계     소계  ...     281     163     163
행정구역(읍면동)별(1) 행정구역(읍면동)별(1)    NaN    NaN    NaN  ...     NaN     NaN     NaN

                                                                    \
                               2017    2018    2019 2020 2021 2022
일반가구수 (가구)    소계              11732   11472   11523    -    -    -
주택보급률 (%)     소계             106.60  110.00  106.44    -    -    -
주택수 (호)       다세대주택             404     404     102    -    -    -
              단독주택             3441    3532    3532    -    -    -
              단독주택.1           2293    2375    2475    -    -    -
              비거주용 건물내 주택        86      89      89    -    -    -
              소계              12506   12619   12265    -    -    -
              아파트              8418    8438    8418    -    -    -
              연립주택              157     156     124    -    -    -
행정구역(읍면동)별(1) 행정구역(읍면동)별(1)     NaN     NaN     NaN  NaN  NaN  NaN


                            행정구역(읍면동)별(1)
일반가구수 (가구)    소계                      NaN
주택보급률 (%)     소계                      NaN
주택수 (호)       다세대주택                   NaN
              단독주택                    NaN
              단독주택.1                  NaN
              비거주용 건물내 주택             NaN
              소계                      NaN
              아파트                     NaN
              연립주택                    NaN
행정구역(읍면동)별(1) 행정구역(읍면동)별(1)           석남동

[10 rows x 176 columns]

In [188]:
# seosan3_T.drop(index=['행정구역(읍면동)별(1)','행정구역(읍면동)별(1)'], columns='행정구역(읍면동)별(1)', inplace=True)
# seosan3 = seosan3_T.droplevel(level=0, axis=1)
# seosan3.loc['세대수'] = np.nan
# seosan3_T.drop(labels=['행정구역(읍면동)별(1)'], axis=0, inplace=True)
seosan3

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,행정구역(읍면동)별(1)
"(일반가구수 (가구), 소계)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,7309,9432,10699,11732,11472,11523,-,-,-,NaN
"(주택보급률 (%), 소계)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,141.26,112.62,111.95,106.60,110.00,106.44,-,-,-,NaN
"(주택수 (호), 다세대주택)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,263,354,386,404,404,102,-,-,-,NaN
"(주택수 (호), 단독주택)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,3121,3357,3843,3441,3532,3532,-,-,-,NaN
"(주택수 (호), 단독주택.1)",다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,...,1818,2014,2246,2293,2375,2475,-,-,-,NaN
"(주택수 (호), 비거주용 건물내 주택)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,99,54,83,86,89,89,-,-,-,NaN
"(주택수 (호), 소계)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,10325,10622,11977,12506,12619,12265,-,-,-,NaN
"(주택수 (호), 아파트)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,6561,6694,7502,8418,8438,8418,-,-,-,NaN
"(주택수 (호), 연립주택)",소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,281,163,163,157,156,124,-,-,-,NaN
세대수,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [192]:
seosan3.reindex(index=['(일반가구수 (가구), 소계)', '세대수', '(주택보급률 (%), 소계)', '(주택수 (호), 다가구주택)', '(주택수 (호), 다세대주택)',
                       '(주택수 (호), 단독주택)', '(주택수 (호), 비거주용건물 내 주택)', '(주택수 (호), 소계)', '(주택수 (호), 아파트)', '(주택수 (호), 연립주택)'])

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,행정구역(읍면동)별(1)
"(일반가구수 (가구), 소계)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
세대수,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택보급률 (%), 소계)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 다가구주택)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 다세대주택)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 단독주택)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 비거주용건물 내 주택)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 소계)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 아파트)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(주택수 (호), 연립주택)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [193]:
seosan3.index = index2
seosan3

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,행정구역(읍면동)별(1)
일반가구수(A)(가구),소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,7309,9432,10699,11732,11472,11523,-,-,-,NaN
세대수,소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,141.26,112.62,111.95,106.60,110.00,106.44,-,-,-,NaN
주택보급률(B)/(A)*100(%),소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,263,354,386,404,404,102,-,-,-,NaN
다가구주택(호),소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,3121,3357,3843,3441,3532,3532,-,-,-,NaN
다세대주택(호),다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,다가구주택,...,1818,2014,2246,2293,2375,2475,-,-,-,NaN
단독주택,소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,99,54,83,86,89,89,-,-,-,NaN
비거주용건물내주택(호),소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,10325,10622,11977,12506,12619,12265,-,-,-,NaN
주택수(B)(호),소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,6561,6694,7502,8418,8438,8418,-,-,-,NaN
아파트(호),소계,소계,소계,소계,소계,소계,소계,소계,소계,소계,...,281,163,163,157,156,124,-,-,-,NaN
연립주택(호),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [195]:
seosan3 = seosan3.iloc[:, 10:]
seosan3.drop(columns='행정구역(읍면동)별(1)', inplace=True)
seosan3

C:\Users\User\AppData\Local\Temp\ipykernel_9628\1981653138.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seosan3.drop(columns='행정구역(읍면동)별(1)', inplace=True)

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
일반가구수(A)(가구),6408,6532,5752,6577,6725,6684,6689,-,-,-,...,7171,7309,9432,10699,11732,11472,11523,-,-,-
세대수,126.00,130.21,144.25,129.69,155.78,162.15,170.12,-,-,-,...,140.69,141.26,112.62,111.95,106.60,110.00,106.44,-,-,-
주택보급률(B)/(A)*100(%),229,274,467,467,479,512,542,-,-,-,...,219,263,354,386,404,404,102,-,-,-
다가구주택(호),3957,4295,4217,4432,5356,5675,5975,-,-,-,...,2982,3121,3357,3843,3441,3532,3532,-,-,-
다세대주택(호),1842,2141,2276,2374,3004,3298,3298,-,-,-,...,1692,1818,2014,2246,2293,2375,2475,-,-,-
단독주택,80,86,85,103,140,151,161,-,-,-,...,70,99,54,83,86,89,89,-,-,-
비거주용건물내주택(호),8074,8505,8297,8530,10476,10838,11379,-,-,-,...,10089,10325,10622,11977,12506,12619,12265,-,-,-
주택수(B)(호),3610,3652,3138,3138,4153,4291,4353,-,-,-,...,6561,6561,6694,7502,8418,8438,8418,-,-,-
아파트(호),198,198,390,390,348,209,348,-,-,-,...,257,281,163,163,157,156,124,-,-,-
연립주택(호),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [196]:
pd.concat([seosan1, seosan2, seosan3], axis=1, join='inner')

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
일반가구수(A)(가구),NaN,NaN,NaN,38771,38980,39161,51585,51945,58274,60287,...,7171,7309,9432,10699,11732,11472,11523,-,-,-
세대수,50286,47864,48548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,140.69,141.26,112.62,111.95,106.60,110.00,106.44,-,-,-
주택보급률(B)/(A)*100(%),98.2,101,100.2,122,135,144,6173,6480,8312,9590,...,219,263,354,386,404,404,102,-,-,-
다가구주택(호),135,186,250,NaN,875,897,2459,2483,1744,2058,...,2982,3121,3357,3843,3441,3532,3532,-,-,-
다세대주택(호),2536,1574,1673,2269,2435,2451,28502,28844,27002,20780,...,1692,1818,2014,2246,2293,2375,2475,-,-,-
단독주택,28887,25234,25363,23211,23208,23057,1057,1067,737,581,...,70,99,54,83,86,89,89,-,-,-
비거주용건물내주택(호),1358,1352,1379,808,810,1057,61827,62203,57918,65343,...,10089,10325,10622,11977,12506,12619,12265,-,-,-
주택수(B)(호),49394,48320,48636,47398,52626,56374,27170,27170,25920,28345,...,6561,6561,6694,7502,8418,8438,8418,-,-,-
아파트(호),16293,18105,18121,18571,23634,27170,2639,2639,2515,2764,...,257,281,163,163,157,156,124,-,-,-
연립주택(호),1543,3221,3229,2539,2539,2639,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- 충주시

In [20]:
chungju1 = pd.read_csv('data/충주시_주택현황 및 보급률(2003~2020).csv', encoding='cp949', header=[0,1,2])
chungju2 = pd.read_csv('data/충주시_주택현황 및 보급률(2019~2021).csv', encoding='cp949')

In [34]:
chungju1

  시군별(1)          2003                                                       \
  시군별(1) 일반가구수(A) (가구) 주택수(B) (호) 단독주택 (호)       아파트 (호) 연립주택 (호) 다세대주택 (호)
  시군별(1)            소계         소계       소계 다가구주택      소계       소계        소계
0    충주시         69066      66622    32075   285   30493     3882       172

                                      ...                 2019          2020  \
  비거주용건물내주택 (호) 주택보급률(B)/(A)*100 (%)  ... 주택보급률(B)/(A)*100 (%) 일반가구수(A) (가구)
             소계                   소계  ...                   소계            소계
0             -                 96.0  ...                120.2         93082

                                                                       \
  주택수(B) (호) 단독주택 (호)        아파트 (호) 연립주택 (호) 다세대주택 (호) 비거주용건물내주택 (호)
          소계       소계  다가구주택      소계       소계        소계            소계
0     109721    42990  19237   53732     3028      4963          5008


  주택보급률(B)/(A)*100 (%)
                    소계
0                117.9

[1 rows x 160 columns]

In [35]:
chungju1_T = chungju1.T
chungju1_T = chungju1_T.unstack(level=0)
chungju1_T

                                 0                                            \
                              2003   2004   2005   2006   2007   2008   2009
다세대주택 (호)            소계        172    512    312    382    423    455    462
단독주택 (호)             다가구주택     285   3605   2070  10068  10555  11095  70042
                     소계      32075  32741  30575  37441  29568  38577  39096
비거주용건물내주택 (호)        소계          -      -      -    964    964    964    964
시군별(1)               시군별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN
아파트 (호)              소계      30493  30890  31811  32591  35820  37005  37013
연립주택 (호)             소계       3882   3882   3406   3454   3700   3742   3742
일반가구수(A) (가구)        소계      69066  72769  53866  53462  52716  70037  69669
주택보급률(B)/(A)*100 (%) 소계       96.0   93.0  123.0  140.0  134.0  115.2  117.0
주택수(B) (호)           소계      66622  68025  66104  74832  70475  80743  81277

                                                                              \
                              2010   2011   2012   2013   2014   2015   2016
다세대주택 (호)            소계        490    895   1743   2404   3084   4471   4682
단독주택 (호)             다가구주택    2155  13916  15218  16475  17292  16602  17229
                     소계      38901  41459  42972  44334  45357  43270  44185
비거주용건물내주택 (호)        소계        690      0    NaN    NaN    NaN   1501   1507
시군별(1)               시군별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN
아파트 (호)              소계      38064  38118  38206  38225  39448  39908  41652
연립주택 (호)             소계       3661   3673   3713   3729   3693   2772   2772
일반가구수(A) (가구)        소계      77015  78443  79689  80954  82239  83585  85152
주택보급률(B)/(A)*100 (%) 소계      106.2  107.3  108.7  109.6  111.4  110.0  111.3
주택수(B) (호)           소계      81806  84145  86634  88692  91582  91922  94798


                              2017    2018    2019    2020 시군별(1)
다세대주택 (호)            소계       4867    4881    4903    4963    NaN
단독주택 (호)             다가구주택   17917   18285   19168   19237    NaN
                     소계      44909   45362   46247   42990    NaN
비거주용건물내주택 (호)        소계       1522    1547    1574    5008    NaN
시군별(1)               시군별(1)    NaN     NaN     NaN     NaN    충주시
아파트 (호)              소계      42806   48981   52629   53732    NaN
연립주택 (호)             소계       2785    2810    3028    3028    NaN
일반가구수(A) (가구)        소계      86367   88711   90191   93082    NaN
주택보급률(B)/(A)*100 (%) 소계      112.2   116.8   120.2   117.9    NaN
주택수(B) (호)           소계      96889  103581  108381  109721    NaN

In [37]:
chungju1_T.drop(index='시군별(1)', columns=[(0,'시군별(1)')], inplace=True)
chungju1 = chungju1_T.droplevel(level=0, axis=1)
chungju1

                             2003   2004   2005   2006   2007   2008   2009  \
다세대주택 (호)            소계       172    512    312    382    423    455    462
단독주택 (호)             다가구주택    285   3605   2070  10068  10555  11095  70042
                     소계     32075  32741  30575  37441  29568  38577  39096
비거주용건물내주택 (호)        소계         -      -      -    964    964    964    964
아파트 (호)              소계     30493  30890  31811  32591  35820  37005  37013
연립주택 (호)             소계      3882   3882   3406   3454   3700   3742   3742
일반가구수(A) (가구)        소계     69066  72769  53866  53462  52716  70037  69669
주택보급률(B)/(A)*100 (%) 소계      96.0   93.0  123.0  140.0  134.0  115.2  117.0
주택수(B) (호)           소계     66622  68025  66104  74832  70475  80743  81277

                             2010   2011   2012   2013   2014   2015   2016  \
다세대주택 (호)            소계       490    895   1743   2404   3084   4471   4682
단독주택 (호)             다가구주택   2155  13916  15218  16475  17292  16602  17229
                     소계     38901  41459  42972  44334  45357  43270  44185
비거주용건물내주택 (호)        소계       690      0    NaN    NaN    NaN   1501   1507
아파트 (호)              소계     38064  38118  38206  38225  39448  39908  41652
연립주택 (호)             소계      3661   3673   3713   3729   3693   2772   2772
일반가구수(A) (가구)        소계     77015  78443  79689  80954  82239  83585  85152
주택보급률(B)/(A)*100 (%) 소계     106.2  107.3  108.7  109.6  111.4  110.0  111.3
주택수(B) (호)           소계     81806  84145  86634  88692  91582  91922  94798

                             2017    2018    2019    2020
다세대주택 (호)            소계      4867    4881    4903    4963
단독주택 (호)             다가구주택  17917   18285   19168   19237
                     소계     44909   45362   46247   42990
비거주용건물내주택 (호)        소계      1522    1547    1574    5008
아파트 (호)              소계     42806   48981   52629   53732
연립주택 (호)             소계      2785    2810    3028    3028
일반가구수(A) (가구)        소계     86367   88711   90191   93082
주택보급률(B)/(A)*100 (%) 소계     112.2   116.8   120.2   117.9
주택수(B) (호)           소계     96889  103581  108381  109721

In [38]:
index3 = ['다세대주택(호)', '다가구주택(호)', '단독주택', '비거주용건물내주택(호)', '아파트(호)', '연립주택(호)',
          '일반가구수(A)(가구)', '주택보급률(B)/(A)*100(%)','주택수(B)(호)']

In [39]:
chungju1.index = index3
chungju1

,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
다세대주택(호),172,512,312,382,423,455,462,490,895,1743,2404,3084,4471,4682,4867,4881,4903,4963
다가구주택(호),285,3605,2070,10068,10555,11095,70042,2155,13916,15218,16475,17292,16602,17229,17917,18285,19168,19237
단독주택,32075,32741,30575,37441,29568,38577,39096,38901,41459,42972,44334,45357,43270,44185,44909,45362,46247,42990
비거주용건물내주택(호),-,-,-,964,964,964,964,690,0,NaN,NaN,NaN,1501,1507,1522,1547,1574,5008
아파트(호),30493,30890,31811,32591,35820,37005,37013,38064,38118,38206,38225,39448,39908,41652,42806,48981,52629,53732
연립주택(호),3882,3882,3406,3454,3700,3742,3742,3661,3673,3713,3729,3693,2772,2772,2785,2810,3028,3028
일반가구수(A)(가구),69066,72769,53866,53462,52716,70037,69669,77015,78443,79689,80954,82239,83585,85152,86367,88711,90191,93082
주택보급률(B)/(A)*100(%),96.0,93.0,123.0,140.0,134.0,115.2,117.0,106.2,107.3,108.7,109.6,111.4,110.0,111.3,112.2,116.8,120.2,117.9
주택수(B)(호),66622,68025,66104,74832,70475,80743,81277,81806,84145,86634,88692,91582,91922,94798,96889,103581,108381,109721

In [21]:
chungju2

      주택현황별(1)    주택현황별(2) 주택현황별(3)    2019    2020    2021
0   일반가구수 (가구)          소계       소계   90191   93082   95350
1  종류별 주택수 (호)           계       소계  108381  109721  110531
2  종류별 주택수 (호)        단독주택       소계   46247   42990   46552
3  종류별 주택수 (호)        단독주택    다가구주택   19168   19237   19439
4  종류별 주택수 (호)         아파트       소계   52629   53732   54313
5  종류별 주택수 (호)        연립주택       소계    3028    3028    3027
6  종류별 주택수 (호)       다세대주택       소계    4903    4963    5012
7  종류별 주택수 (호)  비거주용 건물내주택       소계    1574    5008    1627
8    주택보급률 (%)          소계       소계     120     118     116

In [26]:
chungju2.index=(['일반가구수', '주택수(호)', '단독주택', '다가구주택','아파트','연립주택','다세대주택','비거주용','주택보급률'])
chungju2.drop(columns=['주택현황별(1)', '주택현황별(2)', '주택현황별(3)', '2019', '2020'], inplace=True)
chungju2

          2021
일반가구수    95350
주택수(호)  110531
단독주택     46552
다가구주택    19439
아파트      54313
연립주택      3027
다세대주택     5012
비거주용      1627
주택보급률      116

In [28]:
chungju2.reindex(index=['다세대주택', '다가구주택', '단독주택', '비거주용', '아파트', '연립주택', '일반가구수', '주택보급률', '주택수(호)'])

          2021
다세대주택     5012
다가구주택    19439
단독주택     46552
비거주용      1627
아파트      54313
연립주택      3027
일반가구수    95350
주택보급률      116
주택수(호)  110531

In [41]:
chungju2.index = index3
chungju2

                       2021
다세대주택(호)              95350
다가구주택(호)             110531
단독주택                  46552
비거주용건물내주택(호)          19439
아파트(호)                54313
연립주택(호)                3027
일반가구수(A)(가구)           5012
주택보급률(B)/(A)*100(%)    1627
주택수(B)(호)               116

In [40]:
chungju1

,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
다세대주택(호),172,512,312,382,423,455,462,490,895,1743,2404,3084,4471,4682,4867,4881,4903,4963
다가구주택(호),285,3605,2070,10068,10555,11095,70042,2155,13916,15218,16475,17292,16602,17229,17917,18285,19168,19237
단독주택,32075,32741,30575,37441,29568,38577,39096,38901,41459,42972,44334,45357,43270,44185,44909,45362,46247,42990
비거주용건물내주택(호),-,-,-,964,964,964,964,690,0,NaN,NaN,NaN,1501,1507,1522,1547,1574,5008
아파트(호),30493,30890,31811,32591,35820,37005,37013,38064,38118,38206,38225,39448,39908,41652,42806,48981,52629,53732
연립주택(호),3882,3882,3406,3454,3700,3742,3742,3661,3673,3713,3729,3693,2772,2772,2785,2810,3028,3028
일반가구수(A)(가구),69066,72769,53866,53462,52716,70037,69669,77015,78443,79689,80954,82239,83585,85152,86367,88711,90191,93082
주택보급률(B)/(A)*100(%),96.0,93.0,123.0,140.0,134.0,115.2,117.0,106.2,107.3,108.7,109.6,111.4,110.0,111.3,112.2,116.8,120.2,117.9
주택수(B)(호),66622,68025,66104,74832,70475,80743,81277,81806,84145,86634,88692,91582,91922,94798,96889,103581,108381,109721

In [43]:
pd.concat([chungju1, chungju2], axis=1, join='inner')

,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
다세대주택(호),172,512,312,382,423,455,462,490,895,1743,2404,3084,4471,4682,4867,4881,4903,4963,95350
다가구주택(호),285,3605,2070,10068,10555,11095,70042,2155,13916,15218,16475,17292,16602,17229,17917,18285,19168,19237,110531
단독주택,32075,32741,30575,37441,29568,38577,39096,38901,41459,42972,44334,45357,43270,44185,44909,45362,46247,42990,46552
비거주용건물내주택(호),-,-,-,964,964,964,964,690,0,NaN,NaN,NaN,1501,1507,1522,1547,1574,5008,19439
아파트(호),30493,30890,31811,32591,35820,37005,37013,38064,38118,38206,38225,39448,39908,41652,42806,48981,52629,53732,54313
연립주택(호),3882,3882,3406,3454,3700,3742,3742,3661,3673,3713,3729,3693,2772,2772,2785,2810,3028,3028,3027
일반가구수(A)(가구),69066,72769,53866,53462,52716,70037,69669,77015,78443,79689,80954,82239,83585,85152,86367,88711,90191,93082,5012
주택보급률(B)/(A)*100(%),96.0,93.0,123.0,140.0,134.0,115.2,117.0,106.2,107.3,108.7,109.6,111.4,110.0,111.3,112.2,116.8,120.2,117.9,1627
주택수(B)(호),66622,68025,66104,74832,70475,80743,81277,81806,84145,86634,88692,91582,91922,94798,96889,103581,108381,109721,116

----